# Generated by Django 5.2 on 2026-06-11 10:29

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='+70000000000', max_length=12, null=True, validators=[apps.users.models.validate_phone], verbose_name='Телефон'),
        ),
    ]
